# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0175d9271d69ad6dd431912233db6f9080b51d51fa97bdfbff6e611dc7c2f7173ac83d3d202324221177c642f4db3543e860f9e0ac51bd85e3e053b306128e82

test:
  secret_key_base: f8be70b9386dcb16d6e55887aa8cef749616a3256a775ef0ea2139307916b8c320f5bcd7247f542f707cf9a09e1b5bb183aef526735bd6a85dbde34cda544221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
